// Trains a real logistic regression for L1 (server/src/l1.js) on real labeled
// domains — closing the gap documented in docs/LIMITATIONS.md #3 ("L1
// weights are hand-set, not learned"). Uses the same two live feeds as
// scripts/eval_l1_model.js:
//   - phishing (positive class): mitchellkrogza/Phishing.Database ACTIVE list
//   - legitimate (negative class): opendns/public-domain-lists top domains
// Held-out test split reported honestly — this is not the same data the
// model trains on. Usage: node scripts/train_l1_model.js
const fs = require('fs');
const path = require('path');
const { scoreDomain, ML_FEATURE_NAMES, mlFeatureVector } = require('../server/src/l1');

const PHISH_URL = process.env.PHISH_LIST_URL || 'https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt';
const LEGIT_URL = process.env.LEGIT_LIST_URL || 'https://raw.githubusercontent.com/opendns/public-domain-lists/master/opendns-top-domains.txt';
const SAMPLE_SIZE = +(process.env.SAMPLE_SIZE || 12000);
const WEIGHTS_PATH = path.join(__dirname, '..', 'server', 'data', 'model', 'l1-weights.json');
const REPORT_PATH = path.join(__dirname, '..', 'docs', 'L1_ML_TRAINING_REPORT.md');

async function fetchLines(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`fetch failed ${r.status} for ${url}`);
  const text = await r.text();
  return text.split('\n').map(l => l.trim().toLowerCase()).filter(l => l && !l.startsWith('#'));
}

function sample(arr, n, seed = 1337) {
  const a = arr.slice();
  let s = seed;
  const rand = () => { s = (s * 1103515245 + 12345) & 0x7fffffff; return s / 0x7fffffff; };
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(rand() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a.slice(0, n);
}

// --- tiny logistic regression (batch gradient descent), no deps — same
// implementation style as scripts/train_l3_model.js's fitLogistic ---
function sigmoid(z) { return 1 / (1 + Math.exp(-z)); }
function fitLogistic(X, y, { lr = 0.5, epochs = 3000, l2 = 0.01 } = {}) {
  const d = X[0].length;
  let w = new Array(d).fill(0), b = 0;
  const n = X.length;
  for (let e = 0; e < epochs; e++) {
    const gw = new Array(d).fill(0); let gb = 0;
    for (let i = 0; i < n; i++) {
      const z = X[i].reduce((s, x, j) => s + x * w[j], b);
      const err = sigmoid(z) - y[i];
      for (let j = 0; j < d; j++) gw[j] += err * X[i][j];
      gb += err;
    }
    for (let j = 0; j < d; j++) w[j] -= lr * (gw[j] / n + l2 * w[j]);
    b -= lr * (gb / n);
  }
  return { w, b };
}

function metricsAt(scores, labels, th) {
  let tp = 0, fp = 0, tn = 0, fn = 0;
  for (let i = 0; i < scores.length; i++) {
    const flagged = scores[i] >= th;
    if (labels[i] === 1 && flagged) tp++;
    else if (labels[i] === 1 && !flagged) fn++;
    else if (labels[i] === 0 && flagged) fp++;
    else tn++;
  }
  return { th, recall: tp / (tp + fn || 1), fpr: fp / (fp + tn || 1), precision: tp / (tp + fp || 1) };
}

async function run() {
  console.log('fetching phishing + legit domain lists...');
  const [phishAll, legitAll] = await Promise.all([fetchLines(PHISH_URL), fetchLines(LEGIT_URL)]);
  // balance classes for stable gradient descent — a 39:1 imbalance (like the
  // raw feeds) drags the decision boundary toward "always predict legit"
  const n = Math.min(SAMPLE_SIZE, phishAll.length, legitAll.length);
  const phish = sample(phishAll, n, 1337);
  const legit = sample(legitAll, n, 4242);

  const rows = [...phish.map(d => ({ d, y: 1 })), ...legit.map(d => ({ d, y: 0 }))];
  // deterministic 80/20 split, shuffled once so train/test aren't domain-sorted
  const shuffled = sample(rows, rows.length, 777);
  const splitAt = Math.floor(shuffled.length * 0.8);
  const train = shuffled.slice(0, splitAt), test = shuffled.slice(splitAt);

  const toXY = set => {
    const X = [], y = [];
    for (const { d, y: label } of set) {
      const r = scoreDomain(d);
      if (r.reason === 'official-domain') continue; // no signal to learn from — always 0 by construction
      X.push(mlFeatureVector(r.features));
      y.push(label);
    }
    return { X, y };
  };
  const { X: Xtrain, y: ytrain } = toXY(train);
  const { X: Xtest, y: ytest } = toXY(test);

  console.log(`training on ${Xtrain.length} domains (${ytrain.filter(v => v === 1).length} phishing / ${ytrain.filter(v => v === 0).length} legit)...`);
  const { w, b } = fitLogistic(Xtrain, ytrain);

  const predictProb = x => sigmoid(b + x.reduce((s, xi, i) => s + xi * w[i], 0));
  const testScores = Xtest.map(x => Math.round(predictProb(x) * 100));

  const lines = [];
  lines.push('# L1 ML classifier training report (auto-generated by `node scripts/train_l1_model.js`)\n');
  lines.push(`Generated ${new Date().toISOString()}.\n`);
  lines.push('**무엇을 학습했나**: `server/src/l1.js`가 이미 계산하는 어휘적 특징(브랜드 유사도,');
  lines.push('의심 TLD, 엔트로피 등 — 손으로 짠 휴리스틱과 동일한 입력)을 그대로 특징 벡터로 써서');
  lines.push('실제 라벨링된 도메인으로 로지스틱 회귀를 학습시켰다. 딥러닝이 아니라 13차원');
  lines.push('선형 분류기지만, 가중치 자체는 더 이상 손으로 찍은 값이 아니라 진짜 경사하강법');
  lines.push('학습 결과다.\n');
  lines.push(`- 데이터: 피싱 ${n.toLocaleString()}건 + 정상 ${n.toLocaleString()}건 (클래스 균형을 위해 다운샘플링, 원본 ${phishAll.length.toLocaleString()}건/${legitAll.length.toLocaleString()}건 중)`);
  lines.push(`- 학습/평가 분할: 80% 학습(${Xtrain.length}건) / 20% 홀드아웃 평가(${Xtest.length}건, 학습에 전혀 안 씀)`);
  lines.push(`- 특징: ${ML_FEATURE_NAMES.join(', ')}\n`);

  lines.push('## 홀드아웃 평가 (학습에 쓰지 않은 20%)\n');
  lines.push('| 임계값(ML score≥) | recall | FPR | precision |');
  lines.push('|---|---|---|---|');
  for (const th of [20, 30, 45, 60, 75]) {
    const m = metricsAt(testScores, ytest, th);
    lines.push(`| ${th} | ${(m.recall * 100).toFixed(1)}% | ${(m.fpr * 100).toFixed(2)}% | ${(m.precision * 100).toFixed(1)}% |`);
  }
  lines.push('');
  lines.push('실제 서버는 이 ML 점수를 단독으로 쓰지 않고, 기존 휴리스틱 점수와 `max()`로');
  lines.push('앙상블한다(`server/src/l1.js`) — 둘 중 하나라도 위험하다고 하면 위험으로 판정.');
  lines.push('그래서 ML 모델이 학습 데이터의 편향을 갖고 있어도 기존에 휴리스틱이 잡던 걸');
  lines.push('놓치게 만들 수는 없고, 휴리스틱이 놓치는 패턴을 추가로 잡는 것만 가능하다.');
  lines.push('결합된 시스템의 실제 재현율/오탐률은 `npm run eval:l1`(`docs/L1_EVAL_REPORT.md`)');
  lines.push('참고 — 이 리포트는 ML 모델 단독 성능만 보여준다.\n');

  const weights = { w, b, features: ML_FEATURE_NAMES, trainedAt: new Date().toISOString(), nTrain: Xtrain.length, nTest: Xtest.length };
  fs.mkdirSync(path.dirname(WEIGHTS_PATH), { recursive: true });
  fs.writeFileSync(WEIGHTS_PATH, JSON.stringify(weights, null, 2));
  fs.writeFileSync(REPORT_PATH, lines.join('\n'));
  console.log(lines.join('\n'));
  console.log(`\nweights written to ${path.relative(process.cwd(), WEIGHTS_PATH)}`);
}

run().catch(e => { console.error('training failed:', e.message); process.exit(1); });
